CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login_id" "VARCHAR[20]" UNIQUE NOT NULL,
  "pw" varchar[255] NOT NULL,
  "username" varchar[30] UNIQUE NOT NULL,
  "exp" int NOT NULL,
  "level" int NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "trashcan" (
  "trashcan_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "body" text,
  "user_id" BIGINT NOT NULL,
  "created_at" timestamp,
  "geom" "GEOMETRY(Point,4326)" NOT NULL,
  "image_url" varchar
);

CREATE TABLE "trashcan_categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "trashcan_to_category_map" (
  "trashcan_id" BIGINT,
  "category_id" integer
);

CREATE TABLE "report" (
  "report_id" BIGINT PRIMARY KEY,
  "trashcan_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "opinion" (
  "opinion_id" BIGINT PRIMARY KEY,
  "comment" varchar NOT NULL,
  "trashcan_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "point_history" (
  "point_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL,
  "point" int NOT NULL,
  "reason" varchar[255] NOT NULL,
  "created_at" timestamp
);

COMMENT ON COLUMN "trashcan"."body" IS 'Content of the post';

ALTER TABLE "trashcan" ADD CONSTRAINT "user_posts" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "opinion" ADD FOREIGN KEY ("trashcan_id") REFERENCES "trashcan" ("trashcan_id");

ALTER TABLE "report" ADD FOREIGN KEY ("trashcan_id") REFERENCES "trashcan" ("trashcan_id");

ALTER TABLE "trashcan_to_category_map" ADD FOREIGN KEY ("trashcan_id") REFERENCES "trashcan" ("trashcan_id");

ALTER TABLE "trashcan_to_category_map" ADD FOREIGN KEY ("category_id") REFERENCES "trashcan_categories" ("category_id");

ALTER TABLE "point_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
