name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: true
          reviewers: |
            ARanker
            Jimmy2849
            minjunyeong1
          numberOfReviewers: 0 
          assignees: Jimmy2849
          numOfAssignee: 1
